name: "Smart Events UI :: SDK <-> Openapi compatibility check"
on: [pull_request, push]
jobs:
  run-all-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Fetch latest sandbox/openapi/rhose-api.yaml"
        run: |
          scripts/openapi-sdk/fetch_openapi.sh
      - name: "Check 'git diff' result is 0"
        run: |
          if ! git diff --exit-code; then
            echo "Run scripts/openapi-sdk/fetch_openapi.sh and scripts/openapi-sdk/generate_openapi_client.sh locally. Open PR afterwards."
            exit 1
          else
            echo "SDK and Openapi are synced."
          fi
