name: "Smart Events UI :: Quality Checks"
on: [pull_request, push]
jobs:
  run-all-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test
      - run: npm run test:it
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        if: always() && !cancelled()
        with:
          name: ui-artifacts
          if-no-files-found: warn
          path: |
            **/*.log
            **/cypress/screenshots/**
            **/cypress/videos/**
